#!/usr/bin/env python3
r"""Run safelint against a real-world project and record what it found.

The harness behind ``plan/real-world-validation.md``. It exists so that the
programme's numbers can be regenerated by anyone, against any safelint version,
rather than living in throwaway scripts.

One invocation validates one project for one language::

    scripts/validate_real_world.py \
        --safelint /path/to/isolated/venv/bin/safelint \
        --lang java --preset spring-boot \
        --project /Users/me/sources/safelint_tests/spring-petclinic \
        --label spring-petclinic

and produces two runs - every rule for the language enabled, then stock
defaults - each with the finding counts per rule code, wall time and peak
memory. A markdown summary lands in ``plan/real-world-results/`` (committed);
the raw JSON lands beside it under ``.raw/`` (ignored).

Design points, each the fix for something the first pass got wrong:

* ``--safelint`` should point at the **published** artefact installed in an
  isolated venv (``uv venv v && uv pip install --python v/bin/python
  'safelint[all]==X.Y.Z'``), so what is validated is what a user gets. The
  script prints which binary and version it used so this is never ambiguous.
* The rule list comes from ``<that binary> list-rules --format json``, not from
  whatever ``safelint`` package is importable here. Registry and binary cannot
  drift apart.
* Config is passed with ``--config``. safelint discovers config from the
  **target** path, so a ``safelint.toml`` inside the cloned project would
  otherwise silently override the intended one.
* ``--all-files`` on a polyglot repository lints every language it finds, so
  results are filtered to the extensions of the language under test.
* Vendored trees (``vendor/``, ``target/``, ``third_party/``) are excluded on
  top of safelint's built-in exclusions. The first pass linted dependency
  source inside ``.venv`` directories and called it Go.
* The project's ``HEAD`` SHA is recorded, so a later "fixed and re-ran clean"
  can be reproduced against the same code.
* ``--include`` narrows results to a subtree, for monorepos that hold several
  distinct projects. ``astral-sh/ty`` is the motivating case: its repository is
  a docs stub, and the type checker's real source is ``crates/ty_*`` inside the
  Ruff monorepo, so it can only be validated as a subtree of that clone.
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass, field
import json
from pathlib import Path
import re
import subprocess
import sys
import tempfile
import time
from typing import Any


#: Extensions per language. Mirrors ``safelint.languages``; kept here rather
#: than imported so the harness does not depend on the dev checkout matching
#: the binary under test.
EXTENSIONS: dict[str, tuple[str, ...]] = {
    "python": (".py", ".pyw"),
    "javascript": (".js", ".mjs", ".cjs"),
    "typescript": (".ts", ".tsx", ".as"),
    "java": (".java",),
    "rust": (".rs",),
    "go": (".go",),
    "php": (".php",),
    "c": (".c", ".h"),
    "cpp": (".cpp", ".cxx", ".cc", ".hpp", ".hxx", ".hh"),
}

#: Directory names holding vendored / generated code that safelint does NOT
#: exclude by default. These are what the harness adds.
HARNESS_EXCLUDED_DIR_NAMES: tuple[str, ...] = ("vendor", "target", "third_party")

#: Directory names safelint's own ``exclude_paths`` default already skips.
#: Mirrored rather than imported, for the same reason as EXTENSIONS: the harness
#: must not depend on the dev checkout matching the binary under test.
#:
#: The eligibility check needs these, not just the harness's own: a project whose
#: only files of the target language sit under ``.venv/`` or ``node_modules/``
#: would otherwise satisfy it while the scanner skipped every one of them -
#: ``scanned=0, findings=0`` written up as a clean result, which is the exact
#: false pass that check exists to prevent.
SCANNER_EXCLUDED_DIR_NAMES: tuple[str, ...] = (
    ".venv",
    "venv",
    ".tox",
    ".nox",
    "__pycache__",
    ".pytest_cache",
    ".ruff_cache",
    ".mypy_cache",
    ".ty_cache",
    "build",
    "dist",
    "htmlcov",
    "node_modules",
    "site-packages",
)

#: Every directory name a file can sit under and still never be scanned.
EXCLUDED_DIR_NAMES: tuple[str, ...] = (*HARNESS_EXCLUDED_DIR_NAMES, *SCANNER_EXCLUDED_DIR_NAMES)

#: The harness-added trees as the glob patterns ``extend_exclude_paths`` wants.
#: Derived from the names above so the generated config and the eligibility check
#: cannot drift apart. Only the harness-specific names go here - re-listing
#: safelint's own defaults would add nothing and obscure what the harness changes.
EXTRA_EXCLUDES: tuple[str, ...] = tuple(pattern for name in HARNESS_EXCLUDED_DIR_NAMES for pattern in (f"{name}/**", f"**/{name}/**"))

#: ``--preset`` and ``--label`` are interpolated into a TOML file and a
#: filename respectively. Restricting both to this shape means a quote or
#: newline cannot alter the generated config, and a path separator cannot
#: escape the output directory.
_IDENTIFIER = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$")


#: Seconds before a scan is called hung. Generous on purpose: an all-rules pass
#: over a large monorepo legitimately takes minutes (Ruff's 2006 Rust files take
#: ~25s, and the dataflow rules are the expensive ones), so this is a "something
#: is wrong" bound, not a performance budget. ``--timeout`` overrides it.
DEFAULT_SCAN_TIMEOUT = 1800.0

#: Metadata calls (``--version``, ``git rev-parse``, ``list-rules``) are
#: sub-second in every healthy case; a minute means the binary is not what we
#: think it is, or is waiting on something it will never get.
METADATA_TIMEOUT = 60.0


class HarnessError(RuntimeError):
    """A run could not be measured - the binary crashed or produced no report.

    Raised rather than recorded as zero findings: a crash logged as a clean
    validation is the one outcome this harness must never produce.
    """


#: Which TOML table and key a preset is set through. TypeScript inherits the
#: JavaScript runtime.
PRESET_KEYS: dict[str, tuple[str, str]] = {
    "python": ("python", "framework"),
    "javascript": ("javascript", "runtime"),
    "typescript": ("javascript", "runtime"),
    "java": ("java", "framework"),
    "php": ("php", "framework"),
}


@dataclass(frozen=True)
class Target:
    """Everything one invocation validates: a binary, a language, a project."""

    safelint: Path
    lang: str
    project: Path
    label: str
    preset: str | None = None
    pydantic: bool = False
    include: str | None = None  # keep only findings whose path contains this
    out_dir: Path = Path("plan/real-world-results")
    timeout: float = DEFAULT_SCAN_TIMEOUT


@dataclass
class RunResult:
    """One safelint run, already filtered to the language under test."""

    mode: str
    files_checked: int  # every supported file safelint scanned, ALL languages
    violations: list[dict[str, Any]]
    wall_seconds: float
    peak_rss_mb: float
    stderr: str = ""
    exit_code: int = 0
    counts: dict[str, int] = field(default_factory=dict)

    @property
    def files_with_findings(self) -> int:
        """Distinct files of the language under test that carry at least one finding.

        ``files_checked`` is safelint's own count and includes every language it
        scanned - Ruff's repository holds thousands of Python test fixtures, so
        a Rust run reports 5037 files for 2006 Rust sources. safelint does not
        report per-language scan counts, so this is the honest per-language
        number that CAN be derived from the filtered findings.
        """
        return len({str(v["filepath"]) for v in self.violations})


def _run(cmd: list[str], *, cwd: Path | None = None) -> subprocess.CompletedProcess[str]:
    """Run a short metadata command; never raises on a non-zero exit.

    Bounded by METADATA_TIMEOUT so a binary that blocks - waiting on stdin, say -
    cannot hang the harness before the scan even starts. A timeout is reported as
    an empty result with a non-zero return code, which every caller already
    treats as "this is not a working safelint".
    """
    try:
        return subprocess.run(cmd, cwd=cwd, capture_output=True, text=True, check=False, timeout=METADATA_TIMEOUT)  # noqa: S603 - argv list, no shell
    except subprocess.TimeoutExpired:
        return subprocess.CompletedProcess(cmd, returncode=124, stdout="", stderr=f"timed out after {METADATA_TIMEOUT:.0f}s")


def safelint_version(binary: Path) -> str:
    """Return the version string the binary reports, e.g. ``2.14.0``."""
    out = _run([str(binary), "--version"]).stdout.strip()
    return out.split()[-1] if out else "unknown"


def project_sha(project: Path) -> str:
    """Return the project's ``HEAD`` SHA, or ``not-a-git-checkout``."""
    proc = _run(["git", "-C", str(project), "rev-parse", "HEAD"])
    return proc.stdout.strip() if proc.returncode == 0 else "not-a-git-checkout"


def rules_for(binary: Path, lang: str) -> list[str]:
    """Return every rule name the binary registers for *lang*, from the binary itself."""
    proc = _run([str(binary), "list-rules", "--format", "json"])
    if proc.returncode != 0:
        msg = f"list-rules failed (is --safelint a safelint binary?): {proc.stderr.strip()[:500]}"
        raise HarnessError(msg)
    # A zero exit with output that is not the expected JSON means the binary is
    # not the safelint we think it is (a wrapper script, a shim printing a
    # banner). That is the same user error as a non-zero exit, so it takes the
    # same documented path rather than a JSONDecodeError / KeyError traceback.
    try:
        rules = json.loads(proc.stdout)["rules"]
    except (json.JSONDecodeError, KeyError, TypeError) as exc:
        msg = f"list-rules did not return the expected JSON (is --safelint a safelint binary?): {proc.stdout.strip()[:300]!r}"
        raise HarnessError(msg) from exc
    # Same reasoning one level down, and the TYPES matter as much as the keys:
    # `"languages": null` raises TypeError on the membership test, `"name": 123`
    # yields a non-string rule name that would be interpolated into the generated
    # TOML as `[rules.123]`, and `"languages": "python"` silently degrades the
    # membership test to a substring match (so `go` would match `golang`).
    if not isinstance(rules, list) or not all(_is_rule_entry(r) for r in rules):
        msg = f"list-rules returned entries that are not {{'name': str, 'languages': [str]}} (is --safelint a safelint binary?): {proc.stdout.strip()[:300]!r}"
        raise HarnessError(msg)
    return [r["name"] for r in rules if lang in r["languages"]]


def _is_rule_entry(entry: object) -> bool:
    """Return True if *entry* is a ``{"name": str, "languages": [str]}`` mapping."""
    if not isinstance(entry, dict) or not isinstance(entry.get("name"), str):
        return False
    languages = entry.get("languages")
    return isinstance(languages, list) and all(isinstance(item, str) for item in languages)


def preset_toml(target: Target) -> str:
    """Return the TOML lines that select the framework / runtime preset, if any.

    Keys are grouped by table, because TOML forbids declaring the same table
    twice. ``--lang python --preset django --pydantic`` wants ``framework`` and
    ``pydantic`` in one ``[python]`` table; emitting a header per key produced
    ``Cannot declare ('python',) twice`` and the whole run died on its generated
    config. That combination is exactly what the Django / Flask / FastAPI rows of
    the validation matrix call for.
    """
    tables: dict[str, list[str]] = {}
    section_key = PRESET_KEYS.get(target.lang)
    if target.preset and section_key is not None:
        section, key = section_key
        tables.setdefault(section, []).append(f'{key} = "{target.preset}"')
    if target.pydantic:
        tables.setdefault("python", []).append("pydantic = true")
    return "\n\n".join(f"[{section}]\n" + "\n".join(keys) for section, keys in tables.items())


def write_config(directory: Path, target: Target, rule_names: list[str]) -> None:
    """Write a ``safelint.toml`` enabling *rule_names* (empty for stock defaults)."""
    parts = [
        "# Generated by scripts/validate_real_world.py - do not edit.",
        f"extend_exclude_paths = {json.dumps(list(EXTRA_EXCLUDES))}",
        preset_toml(target),
    ]
    parts.extend(f"[rules.{name}]\nenabled = true" for name in rule_names)
    (directory / "safelint.toml").write_text("\n\n".join(p for p in parts if p) + "\n", encoding="utf-8")


#: Runs one command as its only child and reports that child's exit status,
#: output and peak RSS. ``ru_maxrss`` for ``RUSAGE_CHILDREN`` is the maximum
#: over every child the calling process has ever reaped, so measuring in the
#: harness process would report the larger of the two runs for both. A fresh
#: wrapper per run has exactly one child.
#:
#: The timeout is applied HERE, not around the wrapper: killing the wrapper from
#: outside would leave its scanner child running and still holding the CPU, and
#: the run would be unmeasurable either way. ``subprocess.run`` kills the child
#: on ``TimeoutExpired``, which the wrapper reports as an envelope the parent
#: turns into a HarnessError.
#:
#: This reaches the direct child only - the shape every real scan has, since
#: ``--safelint`` names an executable, not a shell pipeline. A binary that is
#: itself a wrapper script could leave a grandchild behind; that is a limitation
#: of ``subprocess`` timeouts rather than something this bound pretends to solve.
_MEASURED_RUNNER = """
import json, resource, subprocess, sys, time
timeout = float(sys.argv[1])
t0 = time.perf_counter()
try:
    p = subprocess.run(sys.argv[2:], capture_output=True, text=True, check=False, timeout=timeout)
    envelope = {"rc": p.returncode, "out": p.stdout, "err": p.stderr}
except subprocess.TimeoutExpired:
    envelope = {"rc": None, "out": "", "err": "", "timed_out": timeout}
raw = resource.getrusage(resource.RUSAGE_CHILDREN).ru_maxrss
mb = raw / (1024 * 1024) if sys.platform == "darwin" else raw / 1024
envelope.update({"wall": time.perf_counter() - t0, "rss_mb": mb})
print(json.dumps(envelope))
"""


def _path_under(path: str, include: str) -> bool:
    """Return True if *path* lies under the *include* subtree.

    Anchored at a path-segment boundary rather than a raw substring, so
    ``--include crates/ty_`` cannot be satisfied by ``vendor/xcrates/ty_x``, and
    separators are normalised so a Windows-style path is matched the same way.

    Prefix semantics inside the final segment are deliberate: ``crates/ty_`` has
    to match the sibling crates ``ty_python_semantic``, ``ty_ide`` and the rest,
    which a strict whole-segment match would reject.
    """
    haystack = path.replace("\\", "/")
    needle = include.replace("\\", "/").strip("/")
    return bool(needle) and (haystack.startswith(needle) or f"/{needle}" in haystack)


def _measured(cmd: list[str], timeout: float = DEFAULT_SCAN_TIMEOUT) -> dict[str, Any]:
    """Run *cmd* under the one-child wrapper; return its envelope.

    A scan that exceeds *timeout* is a HarnessError, never a zero-findings run -
    the same rule the crash path follows.
    """
    proc = subprocess.run([sys.executable, "-c", _MEASURED_RUNNER, str(timeout), *cmd], capture_output=True, text=True, check=False)  # noqa: S603 - argv list, no shell
    if proc.returncode != 0:
        msg = f"measurement wrapper failed: {proc.stderr.strip()[:500]}"
        raise HarnessError(msg)
    envelope: dict[str, Any] = json.loads(proc.stdout)
    if "timed_out" in envelope:
        msg = f"scan did not finish within {envelope['timed_out']:.0f}s - raise --timeout if this project is legitimately slower"
        raise HarnessError(msg)
    return envelope


def run_safelint(target: Target, config_dir: Path, mode: str) -> RunResult:
    """Run one safelint pass over the project and filter it to the language."""
    # --no-cache: a warm result cache would make a re-run's wall time and memory
    # meaningless, and this harness reports both. The cache key does include the
    # safelint version, so it is correct in production - it is re-runs of the
    # SAME version that would be measured wrong.
    cmd = [str(target.safelint), "check", str(target.project), "--all-files", "--no-cache", "--config", str(config_dir), "--format", "json"]
    env = _measured(cmd, target.timeout)
    # safelint exits 1 when it finds blocking violations, which is a successful
    # run for our purposes; anything else, or a report we cannot parse, is not.
    try:
        payload: dict[str, Any] = json.loads(env["out"])
    except json.JSONDecodeError as exc:
        msg = f"{mode}: safelint exited {env['rc']} without a JSON report - stderr:\n{env['err'].strip()[:1500]}"
        raise HarnessError(msg) from exc
    if env["rc"] not in (0, 1):
        msg = f"{mode}: safelint exited {env['rc']} - stderr:\n{env['err'].strip()[:1500]}"
        raise HarnessError(msg)
    exts = EXTENSIONS[target.lang]
    raw: list[dict[str, Any]] = payload.get("violations", [])
    violations = [v for v in raw if str(v["filepath"]).endswith(exts)]
    if target.include:
        root = target.project.resolve()
        violations = [v for v in violations if _path_under(_project_relative(str(v["filepath"]), root), target.include)]
    files_checked = int(payload.get("summary", {}).get("files_checked", 0))
    result = RunResult(mode, files_checked, violations, float(env["wall"]), float(env["rss_mb"]), env["err"], env["rc"])
    for v in violations:
        code = str(v["code"])
        result.counts[code] = result.counts.get(code, 0) + 1
    return result


def _check_selection_has_files(target: Target) -> None:
    """Fail if the selection holds no file of the target language.

    Two ways to end up scanning nothing while the report still looks clean, both
    of which write a committed zero-findings summary for source that was never
    examined:

    * a mistyped ``--include`` - the filter empties the findings while
      ``files_checked`` stays positive, because it counts the whole project;
    * the **wrong ``--lang``** for the project, which needs no typo at all:
      ``--lang rust`` against a Python repository scans the Python files, filters
      every finding out by extension, and reports ``scanned=N, findings=0``.

    A selection that genuinely holds eligible files and no findings still passes -
    only "nothing was ever eligible" is rejected.
    """
    exts = EXTENSIONS[target.lang]
    for path in target.project.rglob("*"):
        rel = path.relative_to(target.project)
        # is_file() is load-bearing: a DIRECTORY named e.g. ``generated.py``
        # matches the extension test but is not something safelint can scan, so
        # without it an empty subtree could still pass this check.
        if path.is_file() and path.name.endswith(exts) and not _is_excluded(rel) and (not target.include or _path_under(str(rel), target.include)):
            return
    where = f"--include {target.include!r} selects" if target.include else f"{target.project} holds"
    hint = "check the path (it is matched against paths relative to --project)" if target.include else "check --lang"
    msg = f"{where} no scannable {target.lang} file - {hint}, or whether every match sits in an excluded tree ({', '.join(EXCLUDED_DIR_NAMES)})"
    raise HarnessError(msg)


def _project_relative(filepath: str, root: Path) -> str:
    """Return *filepath* relative to *root*, so an include matches only the subtree.

    safelint echoes each path as it was given, and the harness passes an absolute
    project path, so findings come back absolute. Matching ``--include`` against
    the full path let the PROJECT ROOT satisfy it: a checkout at
    ``/tmp/crates/ty_root`` made ``--include crates/ty_`` match every file in the
    repository, silently widening the subtree it claims to narrow.

    A path outside the project is returned unchanged rather than raising; it
    cannot legitimately occur, and failing the whole run over it would be worse
    than letting the include decide.
    """
    try:
        return str(Path(filepath).resolve().relative_to(root))
    except ValueError:
        return filepath


def _is_excluded(rel: Path) -> bool:
    """Return True if any component of *rel* is a vendored / generated directory."""
    return any(part in EXCLUDED_DIR_NAMES for part in rel.parts)


def validate(target: Target) -> list[RunResult]:
    """Run the all-rules pass and the stock-defaults pass; return both."""
    _check_selection_has_files(target)
    names = rules_for(target.safelint, target.lang)
    results: list[RunResult] = []
    with tempfile.TemporaryDirectory(prefix="safelint-validate-") as tmp:
        for mode, enabled in (("all-rules", names), ("defaults", [])):
            config_dir = Path(tmp) / mode
            config_dir.mkdir()
            write_config(config_dir, target, enabled)
            results.append(run_safelint(target, config_dir, mode))
    return results


def _counts_table(result: RunResult) -> str:
    """Markdown table of finding counts per rule code, largest first."""
    if not result.counts:
        return "_no findings_"
    rows = sorted(result.counts.items(), key=lambda kv: (-kv[1], kv[0]))
    total = len(result.violations)
    body = "\n".join(f"| {code} | {n} | {100 * n // total}% |" for code, n in rows)
    return f"| Code | Findings | Share |\n|---|---|---|\n{body}"


def summary_markdown(target: Target, version: str, sha: str, results: list[RunResult]) -> str:
    """Render the committed summary for one project."""
    head = [
        f"# {target.label} - {target.lang}" + (f" / `{target.preset}`" if target.preset else ""),
        "",
        f"- safelint: **{version}** (`{target.safelint}`)",
        f"- project: `{target.project}` @ `{sha}`" + (f", subtree `{target.include}`" if target.include else ""),
        f"- preset: `{target.preset or 'none'}`" + (" + `pydantic = true`" if target.pydantic else ""),
        f"- run: {time.strftime('%Y-%m-%d %H:%M UTC', time.gmtime())}",
        "",
    ]
    for r in results:
        head += [
            f"## {r.mode}",
            "",
            f"- files scanned (all languages): {r.files_checked}",
            f"- {target.lang} files with findings: {r.files_with_findings}",
            f"- findings ({target.lang} files only): **{len(r.violations)}**",
            f"- wall time: {r.wall_seconds:.1f}s, peak RSS: {r.peak_rss_mb:.0f} MB, exit code: {r.exit_code}",
            "",
            _counts_table(r),
            "",
        ]
        if r.stderr.strip():
            head += ["<details><summary>stderr</summary>", "", "```", r.stderr.strip()[:2000], "```", "", "</details>", ""]
    head += ["## Triage", "", "_Classify each rule code: true positive / false positive / debatable. See plan/real-world-validation.md._", ""]
    return "\n".join(head)


def write_outputs(target: Target, version: str, sha: str, results: list[RunResult]) -> Path:
    """Write the markdown summary and raw JSON; return the summary path."""
    stem = f"{target.lang}-{target.label}-{version}-{sha[:7]}"
    target.out_dir.mkdir(parents=True, exist_ok=True)
    raw_dir = target.out_dir / ".raw"
    raw_dir.mkdir(exist_ok=True)
    for r in results:
        (raw_dir / f"{stem}-{r.mode}.json").write_text(json.dumps(r.violations, indent=1), encoding="utf-8")
    summary = target.out_dir / f"{stem}.md"
    summary.write_text(summary_markdown(target, version, sha, results), encoding="utf-8")
    return summary


def _identifier(value: str) -> str:
    """Argparse type: a safe identifier for interpolation into TOML and filenames."""
    if not _IDENTIFIER.fullmatch(value):
        msg = f"must match {_IDENTIFIER.pattern!r} (letters, digits, . _ -), got {value!r}"
        raise argparse.ArgumentTypeError(msg)
    return value


def parse_args(argv: list[str] | None = None) -> Target:
    """Parse the command line into a :class:`Target`."""
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0], formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--safelint", type=Path, default=Path("safelint"), help="safelint binary to validate (an isolated install of the PUBLISHED version)")
    parser.add_argument("--lang", required=True, choices=sorted(EXTENSIONS), help="language under test; results are filtered to its extensions")
    parser.add_argument("--project", required=True, type=Path, help="root of the cloned project")
    parser.add_argument("--label", required=True, type=_identifier, help="short project name used in the output filename, e.g. spring-petclinic")
    parser.add_argument("--preset", type=_identifier, help="framework or runtime preset to enable, e.g. django, spring-boot, bun")
    parser.add_argument("--pydantic", action="store_true", help="also set [python] pydantic = true")
    parser.add_argument("--include", help="keep only findings whose path contains this substring, e.g. crates/ty_ (for a project inside a monorepo)")
    parser.add_argument("--out", type=Path, default=Path("plan/real-world-results"), help="directory for the summary (default: plan/real-world-results)")
    parser.add_argument("--timeout", type=float, default=DEFAULT_SCAN_TIMEOUT, help=f"seconds before a scan is called hung (default: {DEFAULT_SCAN_TIMEOUT:.0f})")
    ns = parser.parse_args(argv)
    if not ns.project.is_dir():
        parser.error(f"--project is not a directory: {ns.project}")
    return Target(ns.safelint, ns.lang, ns.project.resolve(), ns.label, ns.preset, ns.pydantic, ns.include, ns.out, ns.timeout)


def main(argv: list[str] | None = None) -> int:
    """Entry point. A run that cannot be measured exits 2 with the reason on stderr.

    Version discovery is inside the guard, not ahead of it: naming a binary that
    does not exist (or is not executable) is the single likeliest way to invoke
    this wrongly, and it used to surface as a ``FileNotFoundError`` traceback -
    which reads like a bug in the harness rather than a typo in the command.
    """
    target = parse_args(argv)
    try:
        version = safelint_version(target.safelint)
        sha = project_sha(target.project)
        print(f"safelint {version} ({target.safelint}) vs {target.label} @ {sha[:7]} [{target.lang}, preset={target.preset or 'none'}]")
        results = validate(target)
    except (HarnessError, OSError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2
    summary = write_outputs(target, version, sha, results)
    for r in results:
        top = ", ".join(f"{c}:{n}" for c, n in sorted(r.counts.items(), key=lambda kv: -kv[1])[:6])
        print(f"  {r.mode:<10} scanned={r.files_checked:<5} {target.lang}-files-hit={r.files_with_findings:<5} findings={len(r.violations):<6} {r.wall_seconds:5.1f}s {r.peak_rss_mb:5.0f}MB  {top}")
    print(f"summary: {summary}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
